id: A89E94D54
title: Brief Windhorse Practice of Tārā
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:14:50.130896
  last_modified_at: 2022-03-01 01:14:50.130898
