id: A89E94D54
title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:14:50.135311
  last_modified_at: 2022-03-01 01:14:50.135314
