id: A89E94D54
title: Prayer to the Lineage of the Bodhicaryāvatāra
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:14:50.139497
  last_modified_at: 2022-03-01 01:14:50.139500
