id: A89E94D54
title: The Special Teaching of the Wise and Glorious King—Root Text (arranged in Tibetan-English
  verses)
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:14:50.154624
  last_modified_at: 2022-03-01 01:14:50.154627
