id: A89E94D54
title: Prayer to Śāntideva and Dam, Tsang and Jam of Katok
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:14:50.140870
  last_modified_at: 2022-03-01 01:14:50.140872
