id: A89E94D54
title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:14:50.151823
  last_modified_at: 2022-03-01 01:14:50.151826
