id: A89E94D54
title: A Brief Mañjuśrī Sādhana
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:14:50.122906
  last_modified_at: 2022-03-01 01:14:50.122912
