id: A89E94D54
title: 'Nectar of Lunar Crystal: A Prayer to Orgyen Chökyi Wangpo'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:14:50.133914
  last_modified_at: 2022-03-01 01:14:50.133917
