id: A89E94D54
title: Prayer to Machik Labdrön
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:14:50.136849
  last_modified_at: 2022-03-01 01:14:50.136852
